[package]
name = "drmem-drv-hue"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde.default-features = false
serde.features = ["derive", "rc"]

toml.workspace = true
toml.default-features = false

palette.workspace = true

tokio.workspace = true
tokio.default-features = false

tracing.workspace = true
tracing.default-features = false
tracing.features = ["attributes"]

reqwest.workspace = true
reqwest.default-features = false
reqwest.features = ["stream", "json", "rustls"]

rustls.version = "0.23"
rustls.default-features = false
rustls.features = ["ring"]

futures.workspace = true

futures-util = "0.3"

serde_json.workspace = true
serde_json.default-features = false

drmem-api = { path = "../../drmem-api", version = "0.7" }
