[package]
name = "drmem-api"
version = "0.7.0"
authors = ["Rich Neswold <rich.neswold@gmail.com>"]
edition = "2021"
description = "Traits and types used internally by the DrMem control system"
homepage = "https://github.com/DrMemCS/drmem"
repository = "https://github.com/DrMemCS/drmem"
license = "MIT"
categories = ["embedded"]
keywords = ["control-system", "automation"]

[lib]
doctest = false

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono.workspace = true
chrono.default-features = false

toml.workspace = true
toml.default-features = false
toml.features = ["serde"]

tokio.workspace = true
tokio.default-features = false
tokio.features = ["macros"]

tokio-stream.workspace = true
tokio-stream.default-features = false

tracing.workspace = true
tracing.default-features = false

serde.workspace = true
serde.default-features = false

palette.workspace = true
palette.default-features = false

[dev-dependencies]
tokio.workspace = true
tokio.default-features = false

toml.workspace = true
toml.default-features = false
toml.features = ["parse"]

noop-waker = "0.1"
